### ISSUE TITLE
Turisticke znacky "tancuji"

### ISSUE THREAD

**Issue by pavelmachek** [pesvan/OsmHiCheck#5]
OsmHicheck ... pekne!

Jen ty turisticke znacky obcas docela tancujou .. respektive meni
trasu podle zoomu, a neodpovida trasa znacky a trasa cesty pod ni...

http://osm.fit.vutbr.cz/OsmHiCheck/map/#nekdo_kdo_komentuje/15/49.9003/14.6891

**Comment by pesvan** [comment]
Zdravím, 

to bohužel schválně, je to mechanismus pro optimalizaci výkonu - aby se nemuselo načítat tolik bodů, na vyšších úrovních zoomu se nevykreslují všechny uzly trasy. Tuším že od zoomu 16, 17 a blíže by to již mělo odpovídat OSM.

**Comment by pavelmachek** [comment]
Slo by nastavit parametry optimalizace tak aby se to nedelo tak casto? Jo, pri vetsim zoomu to nedela...

**Comment by pesvan** [comment]
Teď by to mělo být přesnější (filtr by neměl filtrovat tak přísně)
